{
 "title": "FastAPI Observability",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(fastapi_app_info{}, app_name)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{fstype!~\"tmpfs|rootfs\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|rootfs\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{method}} {{path}}" }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) / sum(rate(http_request_duration_seconds_count[60m]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[60m])) by (le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{\r\n  status=\"2xx\",\r\n  handler!=\"/metrics\"\r\n}[1h]))\r\n/\r\nsum(increase(http_requests_total{\r\n  handler!=\"/metrics\"\r\n}[1h]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 4xx Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{\r\n  status=\"4xx\",\r\n  handler!=\"/metrics\"\r\n}[1h]))\r\n/\r\nsum(increase(http_requests_total{\r\n  handler!=\"/metrics\"\r\n}[1h]))",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}