apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-metrics
  namespace: monitoring
  labels:
    release: kube-prom  
spec:
  selector:
    matchLabels:
      app: fastapi
  endpoints:
    - port: http        # Must match Service port name
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
